### Get all users
GET http://localhost:8080/api/users
Accept: application/json

### Get user by ID
GET http://localhost:8080/api/users/1
Accept: application/json

### Create new user
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "john.doe2",
  "email": "john.doe2@example.com",
  "password": "securePassword123",
  "role": "USER"
}

### Update user
PUT http://localhost:8080/api/users/1
Content-Type: application/json

{
  "username": "john.doe",
  "email": "john.doe@example.com",
  "password": "newPassword456",
  "role": "ADMIN"
}

### Archive user
DELETE http://localhost:8080/api/users/1
